### ISSUE TITLE
RC2 Windows still "an error occurred"

### ISSUE THREAD

**Issue by theepicflyer** [ambrosechua/Youpp#14]
Still doesn't work. :unamused: 
Here is the error
Unsafe JavaScript attempt to access frame with URL http://localhost:39322/#yazr8JkazmE from frame with URL https://www.youtube.com/embed/8tPnX7OPo0Q?autoplay=1&controls=0&showinfo=0&enablejsapi=1&origin=http%3A%2F%2Flocalhost%3A39322. The frame requesting access has a protocol of 'https', the frame being accessed has a protocol of 'http'. Protocols must match.

It repeats 12 times in attempting to open 1 video.

**Comment by serverwentdown** [comment]
I'm not sure, probably got fixed when I updated NW.js. I don't get any errors anymore, so reopen this issue if you still get them. 😄
